# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JieliJianKang' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JieliJianKang
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit'
  pod 'Toast-Swift','5.0.1'
  pod 'SwiftyAttributes','5.3.0'

end
